import UTABComposerText
import UTABInstruments
import UTABLowering

/// Compatibility accessors for the catalogue authored in `Stdlib/*.utab`.
public enum StandardInstruments {
    public static let catalog: InstrumentCatalog = {
        let root = TextSource(
            "module standard.library\nimport instruments.standard\n",
            fileID: "<standard-library>"
        )
        let loaded = TextModuleLoader().load(root: root, provider: StandardTextModuleProvider())
        let compiled = TextInstrumentCatalogCompiler().compile(
            loaded.modules,
            extending: .init(profiles: [], models: [])
        )
        let diagnostics = loaded.diagnostics.map(\.description) + compiled.diagnostics.map(\.description)
        precondition(
            loaded.succeeded && compiled.succeeded,
            "The bundled UTAB instrument standard library is invalid:\n\(diagnostics.joined(separator: "\n"))"
        )
        return compiled.catalog
    }()

    public static let guitarStandard = tuning("tuning:guitar:standard")
    public static let guitarDropD = tuning("tuning:guitar:drop-d")
    public static let guitarDADGAD = tuning("tuning:guitar:dadgad")
    public static let twelveStringGuitarStandard = tuning("tuning:guitar-12:standard")
    public static let guitarleleStandard = tuning("tuning:guitarlele:standard")
    public static let electricGuitarStandard = tuning("tuning:electric-guitar:standard")
    public static let sopranoUkuleleHighG = tuning("tuning:ukulele:soprano-high-g")
    public static let mandolinStandard = tuning("tuning:mandolin:standard")
    public static let banjoOpenG = tuning("tuning:banjo-5:open-g")
    public static let violinStandard = tuning("tuning:violin:standard")
    public static let violaStandard = tuning("tuning:viola:standard")
    public static let celloStandard = tuning("tuning:cello:standard")
    public static let doubleBassOrchestral = tuning("tuning:double-bass:orchestral")
    public static let electricBassStandard = tuning("tuning:electric-bass:standard")
    public static let fretlessElectricBassStandard = tuning("tuning:electric-bass:fretless-standard")
    public static let concertHarpNatural = tuning("tuning:harp:concert-natural")
    public static let leverHarpCMajor = tuning("tuning:harp:lever-34-c-major")
    public static let renaissanceLuteG = tuning("tuning:lute:renaissance-g")
    public static let arabicOud = tuning("tuning:oud:arabic-c")

    public static let frettedStrings = profile("profile:fretted-strings")
    public static let pluckedCourses = profile("profile:plucked-courses")
    public static let fretlessBowedStrings = profile("profile:fretless-bowed-strings")
    public static let fretlessPluckedStrings = profile("profile:fretless-plucked-strings")
    public static let fourValveBrass = profile("profile:wind:four-valve-brass")
    public static let doubleValveSlideBrass = profile("profile:wind:double-valve-slide-brass")
    public static let harpsichordKeyboard = profile("profile:keyboard:harpsichord")
    public static let pipeOrganConsole = profile("profile:keyboard:pipe-organ-console")
    public static let patchSynthesizer = profile("profile:keyboard:patch-synthesizer")
    public static let pedalHarp = profile("profile:harp:pedal")
    public static let leverHarp = profile("profile:harp:lever")
    public static let dampedMetalPercussion = profile("profile:percussion:damped-metal")
    public static let pedalHiHat = profile("profile:percussion:pedal-hi-hat")
    public static let dampedPitchedPercussion = profile("profile:percussion:damped-pitched")
    public static let shakenPercussion = profile("profile:percussion:shaken")
    public static let handDrum = profile("profile:percussion:hand-drum")
    public static let jingledFrameDrum = profile("profile:percussion:jingled-frame-drum")
    public static let pressureTunedDrumPair = profile("profile:percussion:pressure-tuned-drum-pair")
    public static let doubleHeadedBarrelDrum = profile("profile:percussion:double-headed-barrel-drum")
    public static let squeezableFrameDrum = profile("profile:percussion:squeezable-frame-drum")
    public static let clayPotPercussion = profile("profile:percussion:clay-pot")
    public static let strappedDoubleHeadedDrum = profile("profile:percussion:strapped-double-headed-drum")
    public static let pressureCordDrum = profile("profile:percussion:pressure-cord-drum")
    public static let multiHandDrum = profile("profile:percussion:multi-hand-drum")
    public static let stickDrumSet = profile("profile:percussion:stick-drum-set")
    public static let multiSurfaceBoxDrum = profile("profile:percussion:multi-surface-box-drum")
    public static let scrapedPercussion = profile("profile:percussion:scraped")
    public static let mountedDoubleHeadedDrum = profile("profile:percussion:mounted-double-headed-drum")
    public static let asymmetricDoubleHeadedDrum = profile("profile:percussion:asymmetric-double-headed-drum")
    public static let bossedGongRack = profile("profile:percussion:bossed-gong-rack")
    public static let troughMetallophone = profile("profile:percussion:trough-metallophone")
    public static let resonatedSuspendedMetallophone = profile("profile:percussion:resonated-suspended-metallophone")
    public static let hangingBossedGongSet = profile("profile:percussion:hanging-bossed-gong-set")
    public static let dividedSurfaceSteelPan = profile("profile:percussion:divided-surface-steelpan")
    public static let handpanToneFields = profile("profile:percussion:handpan-tone-fields")
    public static let buzzingBoardLamellophone = profile("profile:percussion:buzzing-board-lamellophone")
    public static let boxLamellophone = profile("profile:percussion:box-lamellophone")
    public static let gourdResonatedXylophone = profile("profile:percussion:gourd-resonated-xylophone")
    public static let leveredCourseZither = profile("profile:zither:levered-courses")
    public static let tiedFretPluckedCourses = profile("profile:strings:tied-fret-plucked-courses")
    public static let spikeFiddle = profile("profile:strings:spike-fiddle")
    public static let rimBlownFlute = profile("profile:wind:rim-blown-flute")
    public static let folkDoubleReed = profile("profile:wind:folk-double-reed")
    public static let frettedSympatheticLute = profile("profile:strings:fretted-sympathetic-lute")
    public static let fretlessSympatheticLute = profile("profile:strings:fretless-sympathetic-lute")
    public static let carnaticFrettedVeena = profile("profile:strings:carnatic-fretted-veena")
    public static let jawariDroneLute = profile("profile:strings:jawari-drone-lute")
    public static let sympatheticBowedLute = profile("profile:strings:sympathetic-bowed-lute")
    public static let sideBlownBambooFlute = profile("profile:wind:side-blown-bamboo-flute")
    public static let handPumpedReedKeyboard = profile("profile:keyboard:hand-pumped-reed")
    public static let bellowsFreeReed = profile("profile:wind:bellows-free-reed")
    public static let bowBetweenStringsFiddle = profile("profile:strings:bow-between-strings-fiddle")
    public static let verticalFrettedLute = profile("profile:strings:vertical-fretted-lute")
    public static let pressureBridgeZither = profile("profile:zither:pressure-bridge")
    public static let fretlessTableZither = profile("profile:zither:fretless-table")
    public static let hammeredBridgeZither = profile("profile:zither:hammered-bridges")
    public static let membraneTransverseFlute = profile("profile:wind:membrane-transverse-flute")
    public static let notchedEndBlownFlute = profile("profile:wind:notched-end-blown-flute")
    public static let freeReedPipeMouthOrgan = profile("profile:wind:free-reed-pipe-mouth-organ")
    public static let movableBridgeLongZither = profile("profile:zither:movable-bridge-long")
    public static let skinSoundboardSpikeLute = profile("profile:strings:skin-soundboard-spike-lute")
    public static let breathAngleEndBlownFlute = profile("profile:wind:breath-angle-end-blown-flute")
    public static let frettedAndBridgedStickZither = profile("profile:zither:fretted-and-bridged-stick")
    public static let doubleRankNotchedBridgeHarpLute = profile("profile:strings:double-rank-notched-bridge-harp-lute")
    public static let skinSoundboardSpikeHarp = profile("profile:strings:skin-soundboard-spike-harp")
    public static let gourdResonatedStruckMusicalBow = profile("profile:strings:gourd-resonated-struck-musical-bow")
    public static let coinStoppedGourdMusicalBow = profile("profile:strings:coin-stopped-gourd-musical-bow")
    public static let splitComplementaryPanpipePair = profile("profile:wind:split-complementary-panpipe-pair")
    public static let bagReservoirChanterAndDrones = profile("profile:wind:bag-reservoir-chanter-and-drones")
    public static let crankedWheelKeyedDroneStrings = profile("profile:strings:cranked-wheel-keyed-drone")
    public static let diatonicFrettedDroneZither = profile("profile:zither:diatonic-fretted-drone")
    public static let americanHammeredCourseZither = profile("profile:zither:american-hammered-courses")
    public static let hindustaniClassicalSingingVoice = profile("profile:voice:hindustani-classical")
    public static let xhosaOvertoneSingingVoice = profile("profile:voice:xhosa-overtone")
    public static let keyboard = profile("profile:keyboard")
    public static let singingVoice = profile("profile:singing-voice")

    public static let guitar = model("instrument:guitar:classical-six-string")
    public static let twelveStringGuitar = model("instrument:guitar:twelve-string")
    public static let guitarlele = model("instrument:guitarlele:standard")
    public static let electricGuitar = model("instrument:guitar:electric-six-string")
    public static let sopranoUkulele = model("instrument:ukulele:soprano")
    public static let mandolin = model("instrument:mandolin:eight-string")
    public static let fiveStringBanjo = model("instrument:banjo:five-string")
    public static let violin = model("instrument:violin:four-string")
    public static let viola = model("instrument:viola:four-string")
    public static let cello = model("instrument:cello:four-string")
    public static let doubleBass = model("instrument:double-bass:four-string")
    public static let electricBass = model("instrument:electric-bass:four-string-fretted")
    public static let fretlessElectricBass = model("instrument:electric-bass:four-string-fretless")
    public static let doubleHorn = model("instrument:horn:double-f-b-flat")
    public static let euphonium = model("instrument:euphonium:b-flat-four-valve")
    public static let tuba = model("instrument:tuba:cc-four-valve")
    public static let bassTrombone = model("instrument:trombone:bass-b-flat")
    public static let doubleManualHarpsichord = model("instrument:harpsichord:double-manual-five-octave")
    public static let threeManualPipeOrgan = model("instrument:pipe-organ:three-manual")
    public static let performanceSynthesizer = model("instrument:synthesizer:performance-61-key")
    public static let concertPedalHarp = model("instrument:harp:concert-pedal-47-string")
    public static let thirtyFourStringLeverHarp = model("instrument:harp:lever-34-string")
    public static let hiHat = model("instrument:percussion:hi-hat")
    public static let tamTam = model("instrument:percussion:tam-tam")
    public static let tubularBells = model("instrument:percussion:tubular-bells")
    public static let maracas = model("instrument:percussion:maracas-pair")
    public static let egyptianDarbuka = model("instrument:percussion:darbuka:egyptian")
    public static let arabicRiq = model("instrument:percussion:riq:arabic")
    public static let arabicDaff = model("instrument:percussion:daff:arabic-unringed")
    public static let northAfricanBendir = model("instrument:percussion:bendir:north-african-snared")
    public static let hindustaniTablaPair = model("instrument:percussion:tabla:hindustani-pair")
    public static let hindustaniPakhawaj = model("instrument:percussion:pakhawaj:hindustani")
    public static let carnaticMridangam = model("instrument:percussion:mridangam:carnatic")
    public static let carnaticKanjira = model("instrument:percussion:kanjira:carnatic")
    public static let carnaticGhatam = model("instrument:percussion:ghatam:carnatic-clay")
    public static let northIndianDholak = model("instrument:percussion:dholak:north-indian")
    public static let punjabiDhol = model("instrument:percussion:dhol:punjabi")
    public static let westAfricanDjembe = model("instrument:percussion:djembe:west-african-rope-tuned")
    public static let westAfricanDunun = model("instrument:percussion:dunun:west-african")
    public static let yorubaTalkingDrum = model("instrument:percussion:talking-drum:yoruba-dundun")
    public static let beadedGourdShekere = model("instrument:percussion:shekere:beaded-gourd")
    public static let cubanCongaSet = model("instrument:percussion:congas:cuban-three-drum")
    public static let cubanBongos = model("instrument:percussion:bongos:cuban-pair")
    public static let cubanTimbales = model("instrument:percussion:timbales:cuban-pair")
    public static let peruvianCajon = model("instrument:percussion:cajon:peruvian")
    public static let brazilianSurdo = model("instrument:percussion:surdo:brazilian")
    public static let brazilianPandeiro = model("instrument:percussion:pandeiro:brazilian")
    public static let cubanGuiro = model("instrument:percussion:guiro:cuban-gourd")
    public static let nagadoDaiko = model("instrument:percussion:taiko:nagado-daiko")
    public static let koreanJanggu = model("instrument:percussion:janggu:korean-pungmul")
    public static let koreanBuk = model("instrument:percussion:buk:korean-barrel")
    public static let balineseKendangPair = model("instrument:percussion:kendang:balinese-lanang-wadon-pair")
    public static let javaneseBonangBarungPelog = model("instrument:percussion:bonang:javanese-barung-pelog")
    public static let javaneseSaronBarungPelog = model("instrument:percussion:saron:javanese-barung-pelog")
    public static let javaneseGenderBarungPelog = model("instrument:percussion:gender:javanese-barung-pelog")
    public static let javaneseGongAgengKempulSet = model("instrument:percussion:gong:javanese-ageng-kempul-set")
    public static let trinidadHighTenorSteelpan = model("instrument:percussion:steelpan:trinidad-high-tenor-d4-g6")
    public static let dMinorNineNoteHandpan = model("instrument:percussion:handpan:d-minor-nine-note")
    public static let shonaMbiraDzavadzimu = model("instrument:percussion:mbira:shona-dzavadzimu-24-key")
    public static let hughTraceyTrebleKalimbaG = model("instrument:percussion:kalimba:hugh-tracey-treble-17-g")
    public static let mandeBalaFourteenKey = model("instrument:percussion:balafon:mande-bala-fourteen-key")
    public static let turkishOud = model("instrument:oud:turkish-bolahenk-six-course")
    public static let turkishQanun = model("instrument:qanun:turkish-24-course-mandalli")
    public static let shortNeckBaglama = model("instrument:baglama:turkish-short-neck-seven-string")
    public static let persianKamancheh = model("instrument:kamancheh:persian-modern-four-string")
    public static let turkishKizNey = model("instrument:ney:turkish-kiz-a2")
    public static let armenianADuduk = model("instrument:duduk:armenian-a-apricot")
    public static let turkishKabaZurna = model("instrument:zurna:turkish-kaba")
    public static let hindustaniKharajPanchamSitar = model("instrument:sitar:hindustani-kharaj-pancham-18-string")
    public static let hindustaniSarod = model("instrument:sarod:hindustani-modern-23-string")
    public static let thanjavurSaraswatiVeena = model("instrument:veena:saraswati-thanjavur-seven-string")
    public static let hindustaniMirajTanpura = model("instrument:tanpura:hindustani-miraj-four-string")
    public static let hindustaniClassicalSarangi = model("instrument:sarangi:hindustani-classical-37-string")
    public static let hindustaniBbBansuri = model("instrument:bansuri:hindustani-b-flat-six-hole")
    public static let hindustaniShehnai = model("instrument:shehnai:hindustani-seven-hole")
    public static let northIndianScaleChangerHarmonium = model("instrument:harmonium:north-indian-scale-changer-39-key")
    public static let modernErhu = model("instrument:erhu:modern-d-a")
    public static let concertPipa = model("instrument:pipa:chinese-concert-four-string")
    public static let twentyOneStringGuzheng = model("instrument:guzheng:chinese-21-string-pentatonic")
    public static let sevenStringGuqin = model("instrument:guqin:chinese-seven-string-standard")
    public static let chineseChromaticYangqin = model("instrument:yangqin:chinese-concert-chromatic")
    public static let chineseDiziD = model("instrument:dizi:chinese-d-key-six-hole")
    public static let chineseGXiao = model("instrument:xiao:chinese-g-key-eight-hole")
    public static let centralChineseXiaosheng = model("instrument:sheng:central-chinese-xiaosheng-17-pipe")
    public static let northernChineseSuona = model("instrument:suona:northern-chinese-standard")
    public static let japaneseThirteenStringKoto = model("instrument:koto:japanese-13-string-hirajoshi")
    public static let japaneseHosozaoShamisen = model("instrument:shamisen:japanese-hosozao-honchoshi")
    public static let kinkoShakuhachiOneEight = model("instrument:shakuhachi:kinko-1.8-d4")
    public static let japaneseGagakuSho = model("instrument:sho:japanese-gagaku-17-pipe")
    public static let koreanJeongakGayageum = model("instrument:gayageum:korean-jeongak-12-string")
    public static let koreanGeomungo = model("instrument:geomungo:korean-six-string")
    public static let koreanJeongakDaegeum = model("instrument:daegeum:korean-jeongak-six-hole")
    public static let koreanHaegeum = model("instrument:haegeum:korean-traditional-two-string")
    public static let mandinkaTwentyOneStringKora = model("instrument:kora:mandinka-21-string")
    public static let wasuluSixStringDonsoNgoni = model("instrument:ngoni:wasulu-donso-six-string")
    public static let xhosaUhadiMusicalBow = model("instrument:musical-bow:xhosa-uhadi")
    public static let brazilianCapoeiraBerimbau = model("instrument:berimbau:brazilian-capoeira")
    public static let bolivianTenStringCharango = model("instrument:charango:bolivian-ten-string-natural")
    public static let venezuelanLlaneroCuatro = model("instrument:cuatro:venezuelan-llanero-four-string")
    public static let andeanSevenHoleQuena = model("instrument:quena:andean-seven-hole-g")
    public static let aymaraChallaSikuPair = model("instrument:siku:aymara-challa-ira-arka")
    public static let argentineRheinischeBandoneon = model("instrument:bandoneon:argentine-rheinische-142-tone")
    public static let greatHighlandBagpipe = model("instrument:bagpipe:great-highland")
    public static let frenchSixStringHurdyGurdy = model("instrument:hurdy-gurdy:french-six-string")
    public static let virginiaFourStringAppalachianDulcimer = model("instrument:dulcimer:appalachian-virginia-four-string-daa")
    public static let americanTwelveFifteenHammeredDulcimer = model("instrument:dulcimer:hammered-american-12-15")
    public static let hindustaniKhayalVoice = model("instrument:voice:hindustani-khayal")
    public static let thembuXhosaUmngqokoloVoice = model("instrument:voice:xhosa-umngqokolo")
    public static let renaissanceLute = model("instrument:lute:renaissance-six-course")
    public static let oud = model("instrument:oud:arabic-six-course")
    public static let piano = model("instrument:piano:88-key")
    public static let voice = model("instrument:voice:generic")

    private static func tuning(_ id: String) -> InstrumentTuningDefinition {
        guard let value = catalog.tunings.first(where: { $0.id.rawValue == id }) else {
            preconditionFailure("Missing standard tuning '\(id)'")
        }
        return value
    }

    private static func profile(_ id: String) -> InstrumentProfileDefinition {
        guard let value = catalog.profiles.first(where: { $0.id.rawValue == id }) else {
            preconditionFailure("Missing standard profile '\(id)'")
        }
        return value
    }

    private static func model(_ id: String) -> InstrumentModelDefinition {
        guard let value = catalog.models.first(where: { $0.id.rawValue == id }) else {
            preconditionFailure("Missing standard instrument model '\(id)'")
        }
        return value
    }
}
